### ISSUE TITLE
MVPs

### ISSUE THREAD

**Issue by simcha-c** [mgoetzke/flack#1]
Live Chat MVP:
- [x] can you add a bullet point that it will be live chat between multiple users?

Channels:
- [x] admins cant delete/approve users. Lets take that out.
- [x] private channel members can add other members to the channel.

Team DM's
- [x] lets add bullet points that are different than the regular DM mvp.

Otherwise, looks good!

**Comment by mgoetzke** [comment]
Thanks, Simcha! Updated the MVPs to match your comments.
