### ISSUE TITLE
Schema

### ISSUE THREAD

**Issue by simcha-c** [mgoetzke/flack#2]
users table looks good!

`channels` table:
- [x] lets add a `topic` column

`messages` table:
- [x] lets make this a polymorphic table. Messages can be either from a channel or dm.

`dms` table:
- [x] i dont think theres a admin for a dm. lets take that out.

`memberships` table:
- [x] lets make this table a polymorphic table as well. Either channel or dm.

**Comment by mgoetzke** [comment]
Updated according to your comments
